apiVersion: v1
kind: ImageStream
metadata:
  name: jenkins
spec: 
  tags:
    - annotations:
        openshift.io/imported-from: 'openshift/jenkins-2-centos7:latest'
      from:
        kind: DockerImage
        name: 'openshift/jenkins-2-centos7:latest'
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
